apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map
data:
  DB_HOST: postgres-cluster-ip-service-dev-db
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: postgres
  PORT: "8080"
  MODE: dev

